// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6u-E4v1cy5Jr_9spYbNGc6cz_JnHgSLA',
    appId: '1:791882969535:web:2b0391a256674b429d310a',
    messagingSenderId: '791882969535',
    projectId: 'tapit-bce31',
    authDomain: 'tapit-bce31.firebaseapp.com',
    storageBucket: 'tapit-bce31.firebasestorage.app',
    measurementId: 'G-JBM66RJ6WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVygYvPhnWU7jDXA6E9IiZoTY7-WRrnQ',
    appId: '1:791882969535:android:11c4d61411a0c2329d310a',
    messagingSenderId: '791882969535',
    projectId: 'tapit-bce31',
    storageBucket: 'tapit-bce31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbTHJEIQs9oLfSbUA9V0Fd85PehMvE_w',
    appId: '1:791882969535:ios:9fd4e9782e28a4769d310a',
    messagingSenderId: '791882969535',
    projectId: 'tapit-bce31',
    storageBucket: 'tapit-bce31.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGbTHJEIQs9oLfSbUA9V0Fd85PehMvE_w',
    appId: '1:791882969535:ios:9fd4e9782e28a4769d310a',
    messagingSenderId: '791882969535',
    projectId: 'tapit-bce31',
    storageBucket: 'tapit-bce31.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6u-E4v1cy5Jr_9spYbNGc6cz_JnHgSLA',
    appId: '1:791882969535:web:5628d9efcc77d2439d310a',
    messagingSenderId: '791882969535',
    projectId: 'tapit-bce31',
    authDomain: 'tapit-bce31.firebaseapp.com',
    storageBucket: 'tapit-bce31.firebasestorage.app',
    measurementId: 'G-FZMLH5FJ5G',
  );

}