import 'package:flutter/material.dart';
// import 'package:device_preview/device_preview.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this
import 'firebase_options.dart'; // This is generated by flutterfire configure
import 'screens/profile_screen.dart';
import 'screens/leaderboard_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print("✅ Firebase Initialized");

  runApp(
    // DevicePreview(
    // builder: (context) =>
    TapTheDotApp(),
    // ),
  );
}

class TapTheDotApp extends StatelessWidget {
  const TapTheDotApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tap the Dot',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Colors.black,
        primaryColor: Colors.deepPurple,
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.deepPurple,
            foregroundColor: Colors.white,
            textStyle: const TextStyle(fontSize: 18),
          ),
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const ProfileScreen(),
        '/leaderboard': (context) => const LeaderboardScreen(),
      },
    );
  }
}
